import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { getPages } from "../../../sanity/sanity-utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const pages = await getPages();
  return (
    <html lang="en">

      <body
       className="mx-w-5xl mx-auto px-20"
      >
        <header>
                  <div className="block pb-20"> 
                    <Link href="/" className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold my-20"> Home </Link>

                      {pages.map((page) => (
                          <Link href={`/pages/${page.slug}`} key={page._id} className="px-4 justify-end text-end">{page?.name}</Link>  
                      ))}
                  </div>
        </header>
        {children}
      </body>
    </html>
  );
}
